language: node_js
node_js:
- node # will use latest node
before_script: # commands to run before the build step
- npm install -g --silent @angular/cli
- npm install -g --silent firebase-tools
script: # the build step
- npm run build -- --prod --build-optimizer
after_success:
- firebase deploy --token $FIREBASE_TOKEN --non-interactive